<?php

declare(strict_types=1);

/**
 * Cron: Auto-generate Draft Commissions
 * Schedule: 1st of every month at 02:00
 * Generates draft commission payments for ALL active customers
 * for the previous month.
 */

$container = require __DIR__ . '/bootstrap.php';

use App\Services\Database;
use App\Services\CommissionService;

$db = $container->get(Database::class);
$commissionService = $container->get(CommissionService::class);

echo "[" . date('Y-m-d H:i:s') . "] Monthly Commission Generation started\n";

// Previous month period
$periodStart = date('Y-m-01', strtotime('first day of last month'));
$periodEnd = date('Y-m-t', strtotime('last day of last month'));
$periodLabel = date('F Y', strtotime('last month'));

echo "Period: {$periodStart} to {$periodEnd} ({$periodLabel})\n";

// Get all active customers with machines
$customers = $db->fetchAll(
    "SELECT DISTINCT c.id, c.name
     FROM customers c
     JOIN machines m ON c.id = m.customer_id
     WHERE c.is_active = 1
     ORDER BY c.name"
);

if (empty($customers)) {
    echo "No active customers with machines found.\n";
    exit(0);
}

$generated = 0;
$skipped = 0;
$errors = 0;

foreach ($customers as $customer) {
    try {
        $result = $commissionService->generateForCustomer(
            (int) $customer['id'],
            $periodStart,
            $periodEnd,
            null // no user — generated by cron
        );

        if ($result['created']) {
            echo "  [NEW] {$customer['name']} - Commission #{$result['id']} - Amount: \${$result['result']['commission_amount']}\n";
        } else {
            echo "  [UPD] {$customer['name']} - Commission #{$result['id']} regenerated\n";
        }
        $generated++;
    } catch (\RuntimeException $e) {
        if (str_contains($e->getMessage(), 'already exists')) {
            echo "  [SKIP] {$customer['name']} - {$e->getMessage()}\n";
            $skipped++;
        } else {
            echo "  [ERR] {$customer['name']} - {$e->getMessage()}\n";
            $errors++;
        }
    } catch (\Exception $e) {
        echo "  [ERR] {$customer['name']} - {$e->getMessage()}\n";
        $errors++;
    }
}

echo "\nComplete. Generated: {$generated}, Skipped: {$skipped}, Errors: {$errors}\n";
echo "[" . date('Y-m-d H:i:s') . "] Monthly Commission Generation completed\n";
